# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/module1_hw/module1_hw.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==module1_hw || ORIG_REF_NAME==module1_hw} -quiet] -quiet

# IP: bd/module1_hw/ip/module1_hw_processing_system7_0_1/module1_hw_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==module1_hw_processing_system7_0_1 || ORIG_REF_NAME==module1_hw_processing_system7_0_1} -quiet] -quiet

# IP: bd/module1_hw/ip/module1_hw_axi_gpio_0_1/module1_hw_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==module1_hw_axi_gpio_0_1 || ORIG_REF_NAME==module1_hw_axi_gpio_0_1} -quiet] -quiet

# IP: bd/module1_hw/ip/module1_hw_auto_pc_0/module1_hw_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==module1_hw_auto_pc_0 || ORIG_REF_NAME==module1_hw_auto_pc_0} -quiet] -quiet

# IP: bd/module1_hw/ip/module1_hw_ps7_0_axi_periph_1/module1_hw_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==module1_hw_ps7_0_axi_periph_1 || ORIG_REF_NAME==module1_hw_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/module1_hw/ip/module1_hw_rst_ps7_0_50M_1/module1_hw_rst_ps7_0_50M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==module1_hw_rst_ps7_0_50M_1 || ORIG_REF_NAME==module1_hw_rst_ps7_0_50M_1} -quiet] -quiet

# XDC: /thayerfs/home/f0041yr/workspace/module1/module1.gen/sources_1/bd/module1_hw/module1_hw_ooc.xdc
